### ISSUE TITLE
Thanks - One fix for windows

### ISSUE THREAD

**Issue by MichaelJEpstein** [MatthewAlner/motion-photo-extractor#2]
Thanks a lot for this. Very helpful! Didn't quite work in Windows because it was not writing output as bin file.

I modded:
  File.open("#{file_path}/#{name}_Extracted.jpg", 'w') { |file| file.write(data[0]) }
            File.open("#{file_path}/#{name}_Extracted.mp4", 'w') { |file| file.write(data[1]) }
to:
  File.open("#{file_path}/#{name}_Extracted.jpg", 'wb') { |file| file.write(data[0]) }
            File.open("#{file_path}/#{name}_Extracted.mp4", 'wb') { |file| file.write(data[1]) }

And then it worked perfectly. Not sure how that affects output on other OSes.

**Comment by MatthewAlner** [comment]
Thanks, I made the change still works on OSX so I'v pushed it 😄
